// <auto-generated />
namespace TVAppVNV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ivanstablesareready : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ivanstablesareready));
        
        string IMigrationMetadata.Id
        {
            get { return "201607142043060_Ivan's tables are ready"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
